RegistrationApplication/Models/ErrorViewModel.cs
using System;

namespace RegistrationApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RegistrationApplication/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace RegistrationApplication.Controllers
{
    public class RegistrationController : Controller
    {
        RegistrationAPI _EmployeeAPI = new RegistrationAPI();

        public async Task<IActionResult> Index()
        {
            List<EmployeeDTO> dto = new List<EmployeeDTO>();

            HttpClient client = _EmployeeAPI.InitializeClient();

            HttpResponseMessage res = await client.GetAsync("api/employee");

            //Checking the response is successful or not which is sent using HttpClient    
            if (res.IsSuccessStatusCode)
            {
                //Storing the response details recieved from web api     
                var result = res.Content.ReadAsStringAsync().Result;

                //Deserializing the response recieved from web api and storing into the Employee list    
                dto = JsonConvert.DeserializeObject<List<EmployeeDTO>>(result);

            }
            //returning the employee list to view    
            return View(dto);
        }

        //GET: Employees/Create
        //public IActionResult Create()
        //{
        //    return View();
        //}

        // POST: Employees/Create  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Name,Email,Password,BirthDate,Sullary,TemrsAccepted")] EmployeeDTO Employee)
        {
            if (ModelState.IsValid)
            {
                HttpClient client = _EmployeeAPI.InitializeClient();

                var content = new StringContent(JsonConvert.SerializeObject(Employee), Encoding.UTF8, "application/json");
                HttpResponseMessage res = client.PostAsync("api/Employee", content).Result;
                if (res.IsSuccessStatusCode)
                {
                    return RedirectToAction("Create");
                }
            }
            return View(Employee);
        }

        // GET: Employees/Edit/1  
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            List<EmployeeDTO> dto = new List<EmployeeDTO>();
            HttpClient client = _EmployeeAPI.InitializeClient();
            HttpResponseMessage res = await client.GetAsync("api/Employee");

            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                dto = JsonConvert.DeserializeObject<List<EmployeeDTO>>(result);
            }

            var Employee = dto.SingleOrDefault(m => m.Id == id);
            if (Employee == null)
            {
                return NotFound();
            }

            return View(Employee);
        }

        // POST: Employees/Edit/1  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(long id, [Bind("Id,Name,Email,Password,BirthDate,Sullary,TemrsAccepted")] EmployeeDTO Employee)
        {
            if (id != Employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                HttpClient client = _EmployeeAPI.InitializeClient();

                var content = new StringContent(JsonConvert.SerializeObject(Employee), Encoding.UTF8, "application/json");
                HttpResponseMessage res = client.PutAsync("api/Employee", content).Result;
                if (res.IsSuccessStatusCode)
                {
                    return RedirectToAction("Create");
                }
            }
            return View(Employee);
        }

        // GET: Employees/Delete/1  
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            List<EmployeeDTO> dto = new List<EmployeeDTO>();
            HttpClient client = _EmployeeAPI.InitializeClient();
            HttpResponseMessage res = await client.GetAsync("api/Employee");

            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                dto = JsonConvert.DeserializeObject<List<EmployeeDTO>>(result);
            }

            var Employee = dto.SingleOrDefault(m => m.Id == id);
            if (Employee == null)
            {
                return NotFound();
            }

            return View(Employee);
        }

        // POST: Employees/Delete/5  
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(long id)
        {
            HttpClient client = _EmployeeAPI.InitializeClient();
            HttpResponseMessage res = client.DeleteAsync($"api/Employee/{id}").Result;
            if (res.IsSuccessStatusCode)
            {
                return RedirectToAction("Create");
            }

            return NotFound();
        }
    }
}

RegistrationApplication/Views/Home/Create.cshtml
@model RegistrationApplication.EmployeeDTO

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<strong>Create</strong>

<form asp-action="Create">
    <div class="form-horizontal">
        <strong>Employee</strong>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Password" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BirthDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Sullary" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Sullary" class="form-control" />
                <span asp-validation-for="Sullary" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}  

RegistrationApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RegistrationApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Registration" asp-action="Create">RegistrationApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registration" asp-action="Create">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registration" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - RegistrationApplication - <a asp-area="" asp-controller="Registration" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>